baseURL = "https://xr1s.me"
buildExpired = true
buildFuture = true
hasCJKLanguage = true
languageCode = "zh-CN"
title = "克莉丝随笔"

[author]
email = "std.xris@gmail.com"
name = "xr1s"

[markup.highlight]
lineNos = true
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
weight = 1

[module]
[[module.imports]]
path = "github.com/xr1s/hugo-theme-texify"

[permalinks]
posts = "/:year/:month/:day/:filename/"

[params]
customCSS = ["css/custom.css"]
description = "克莉丝随笔"
footnote = """
Follow me on <a class=link href="https://github.com/xr1s">GitHub</a> or
<a class=link href=/index.xml>RSS</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
"""
since = 2018
emphasisWithDots = true
toc = true

[params.math]
enable = true
use = "katex"

[params.giscus]
enable = true
script = """<script src="https://giscus.app/client.js"
        data-repo="xr1s/xr1s.github.io"
        data-repo-id="R_kgDOIOi8SA"
        data-category="Announcements"
        data-category-id="DIC_kwDOIOi8SM4CW002"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="zh-CN"
        crossorigin="anonymous"
        async>
</script>"""
